package identity

import (
	"net/http"

	identityapplication "github.com/domainry/domainry-identity/internal/application/identity"
)

type routeRegistrar interface {
	HandleFunc(string, func(http.ResponseWriter, *http.Request))
}

func (h *IdentityHandler) RegisterRoutes(mux routeRegistrar) {
	mux.HandleFunc("GET /identity/effective-menus", h.EffectiveMenus)
	mux.HandleFunc("GET /identity/departments", h.identityPermission("identity.departments.read", h.listIdentityDepartments))
	mux.HandleFunc("GET /identity/departments/{departmentID}", h.identityPermission("identity.departments.read", h.getIdentityDepartment))
	mux.HandleFunc("GET /identity/departments/{departmentID}/versions", h.identityPermission("identity.departments.read", h.identityAuthoringVersions("identity.department", "identity_department", "departmentID", "identity_department_created", "identity_department_updated")))
	mux.HandleFunc("POST /identity/departments", h.identityPermission("identity.departments.write", h.createIdentityDepartment))
	mux.HandleFunc("POST /identity/departments/{departmentID}/validate", h.identityPermission("identity.departments.write", h.validateIdentityDepartmentAuthoring))
	mux.HandleFunc("PATCH /identity/departments/{departmentID}", h.identityPermission("identity.departments.write", h.updateIdentityDepartment))
	mux.HandleFunc("GET /identity/users", h.identityPermission("identity.users.read", h.listIdentityUsers))
	mux.HandleFunc("GET /identity/users/search", h.identityPermission("identity.users.read", h.searchIdentityUsers))
	mux.HandleFunc("GET /identity/users/directory/search", h.identityPermission("identity.users.read", h.searchIdentityUserDirectory))
	mux.HandleFunc("GET /identity/users/{userID}", h.identityPermissionOrSelf("identity.users.read", "userID", h.getIdentityUser))
	mux.HandleFunc("GET /identity/users/{userID}/deletion-impact", h.identityPermission("identity.users.write", h.getIdentityUserDeletionImpact))
	mux.HandleFunc("GET /identity/users/{userID}/disable-impact", h.identityPermission("identity.security.write", h.getIdentityUserDisableImpact))
	mux.HandleFunc("GET /identity/users/{userID}/versions", h.identityPermission("identity.users.read", h.identityAuthoringVersions("identity.user", "identity_user", "userID", "identity_user_created", "identity_user_updated", "identity_user_disabled", "identity_user_enabled", "identity_user_deleted")))
	mux.HandleFunc("POST /identity/users", h.identityPermission("identity.users.write", h.createIdentityUser))
	mux.HandleFunc("POST /identity/users/{userID}/validate", h.identityPermission("identity.users.write", h.validateIdentityUserAuthoring))
	mux.HandleFunc("PATCH /identity/users/{userID}", h.identityPermission("identity.users.write", h.updateIdentityUser))
	mux.HandleFunc("DELETE /identity/users/{userID}", h.identityPermission("identity.users.write", h.deleteIdentityUser))
	mux.HandleFunc("POST /identity/users/{userID}/disable", h.identityPermission("identity.security.write", h.disableIdentityUser))
	mux.HandleFunc("POST /identity/users/{userID}/enable", h.identityPermission("identity.security.write", h.enableIdentityUser))
	mux.HandleFunc("GET /identity/workforce", h.identityPermission("identity.workforce.read", h.listIdentityWorkforceProfiles))
	mux.HandleFunc("GET /identity/workforce/search", h.identityPermission("identity.workforce.read", h.searchIdentityWorkforceProfiles))
	mux.HandleFunc("POST /identity/workforce/onboard", h.identityPermission("identity.workforce.write", h.onboardIdentityWorkforce))
	mux.HandleFunc("POST /identity/workforce/transfers/batch", h.identityPermission("identity.workforce.write", h.applyIdentityWorkforceTransferBatch))
	mux.HandleFunc("GET /identity/workforce/{profileID}", h.identityPermission("identity.workforce.read", h.getIdentityWorkforceProfile))
	mux.HandleFunc("GET /identity/workforce/{profileID}/detail", h.identityPermission("identity.workforce.read", h.getIdentityWorkforceDetail))
	mux.HandleFunc("GET /identity/workforce/{profileID}/assignable-roles", h.identityPermission("identity.roles.write", h.listIdentityAssignableWorkforceRoles))
	mux.HandleFunc("POST /identity/workforce", h.identityPermission("identity.workforce.write", h.upsertIdentityWorkforceProfile))
	mux.HandleFunc("PATCH /identity/workforce/{profileID}", h.identityPermission("identity.workforce.write", h.upsertIdentityWorkforceProfile))
	mux.HandleFunc("POST /identity/workforce/{profileID}/validate", h.identityPermission("identity.workforce.write", h.validateIdentityWorkforceProfile))
	mux.HandleFunc("POST /identity/workforce/{profileID}/terminate", h.identityPermission("identity.workforce.write", h.terminateIdentityWorkforceProfile))
	mux.HandleFunc("POST /identity/workforce/{profileID}/rehire", h.identityPermission("identity.workforce.write", h.rehireIdentityWorkforce))
	mux.HandleFunc("POST /identity/workforce/{profileID}/lifecycle", h.identityPermission("identity.workforce.write", h.applyIdentityWorkforceLifecycle))
	mux.HandleFunc("GET /identity/workforce/{profileID}/assignments", h.identityPermission("identity.workforce.read", h.listIdentityWorkforceAssignments))
	mux.HandleFunc("POST /identity/workforce/{profileID}/assignments", h.identityPermission("identity.workforce.write", h.upsertIdentityWorkforceAssignment))
	mux.HandleFunc("POST /identity/workforce/{profileID}/assignments/validate", h.identityPermission("identity.workforce.write", h.validateIdentityWorkforceAssignment))
	mux.HandleFunc("GET /identity/profile-bindings/{objectKey}/{profileID}", h.Authenticated(h.getIdentityProfileBinding))
	mux.HandleFunc("POST /identity/profile-bindings/{objectKey}/{profileID}/commands", h.Authenticated(h.executeIdentityProfileBindingCommand))
	mux.HandleFunc("GET /identity/principal-context", h.Authenticated(h.getIdentityPrincipalContext))
	mux.HandleFunc("GET /identity/users/{userID}/security", h.identityPermissionOrSelf("identity.users.read", "userID", h.identityUserSecurity))
	mux.HandleFunc("GET /identity/users/{userID}/effective-access", h.Authenticated(h.getIdentityEffectiveAccess))
	mux.HandleFunc("POST /identity/access/explain", h.Authenticated(h.explainIdentityEffectiveAccess))
	mux.HandleFunc("GET /identity/access/reverse-index", h.identityPermission("identity.roles.read", h.getIdentityAccessReverseIndex))
	mux.HandleFunc("GET /identity/access/reports", h.identityPermission("identity.roles.read", h.getIdentityAccessGovernanceReports))
	mux.HandleFunc("POST /identity/access-reviews", h.identityPermission("identity.roles.write", h.createIdentityAccessReview))
	mux.HandleFunc("GET /identity/access-reviews", h.identityPermission("identity.roles.read", h.listIdentityAccessReviews))
	mux.HandleFunc("POST /identity/access-review-items/{itemID}/decision", h.identityPermission("identity.roles.write", h.decideIdentityAccessReviewItem))
	mux.HandleFunc("POST /identity/users/{userID}/unlock", h.identityPermission("identity.security.write", h.unlockIdentityUser))
	mux.HandleFunc("POST /identity/users/{userID}/force-logout", h.identityPermission("identity.security.write", h.forceLogoutIdentityUser))
	mux.HandleFunc("DELETE /identity/users/{userID}/mfa/{factorID}", h.identityPermission("identity.security.write", h.revokeIdentityUserMFAFactor))
	mux.HandleFunc("GET /identity/users/{userID}/role-assignments", h.identityPermissionOrSelf("identity.users.read", "userID", h.listIdentityUserRoleAssignments))
	mux.HandleFunc("GET /identity/users/{userID}/role-assignments/search", h.identityPermissionOrSelf("identity.users.read", "userID", h.searchIdentityUserRoleAssignments))
	mux.HandleFunc("GET /identity/users/{userID}/assignable-roles", h.identityPermission("identity.roles.write", h.listIdentityAssignableRoles))
	mux.HandleFunc("PUT /identity/users/{userID}/account-and-roles", h.identityPermissions([]string{"identity.users.write", "identity.roles.write"}, h.upsertIdentityUserWithRoles))
	mux.HandleFunc("GET /identity/users/{userID}/role-assignments/versions", h.identityPermission("identity.roles.read", h.identityAuthoringVersions("identity.user_role_assignment", "identity_user", "userID", "identity_user_role_assigned", "identity_user_role_removed")))
	mux.HandleFunc("POST /identity/users/{userID}/role-assignments", h.identityPermission("identity.roles.write", h.assignIdentityUserRole))
	mux.HandleFunc("POST /identity/users/{userID}/role-assignments/validate", h.identityPermission("identity.roles.write", h.validateIdentityUserRoleAssignmentAuthoring))
	mux.HandleFunc("DELETE /identity/users/{userID}/role-assignments/{roleID}", h.identityPermission("identity.roles.write", h.removeIdentityUserRole))
	mux.HandleFunc("POST /identity/entitlements/batch", h.identityPermission("identity.roles.write", h.applyIdentityEntitlementBatch))
	mux.HandleFunc("GET /identity/role-requests", h.identityPermission("identity.roles.read", h.listIdentityRoleRequests))
	mux.HandleFunc("POST /identity/role-requests/{requestID}/approve", h.identityPermission("identity.roles.write", h.approveIdentityRoleRequest))
	mux.HandleFunc("POST /identity/role-requests/{requestID}/reject", h.identityPermission("identity.roles.write", h.rejectIdentityRoleRequest))
	h.registerIdentityAction(mux, identityapplication.IdentityActionRolesList, h.listIdentityRoles)
	h.registerIdentityAction(mux, identityapplication.IdentityActionRolesGet, h.getIdentityRole)
	h.registerIdentityAction(mux, identityapplication.IdentityActionRolesGovernanceDetail, h.getIdentityRoleGovernanceDetail)
	h.registerIdentityAction(mux, identityapplication.IdentityActionRolesVersions, h.identityAuthoringVersions("identity.role", "identity_role", "roleID", "identity_role_created", "identity_role_updated", "identity_role_disabled", "identity_role_enabled", "identity_role_deleted"))
	h.registerIdentityAction(mux, identityapplication.IdentityActionRolesValidateGovernance, h.validateIdentityGovernance)
	h.registerIdentityAction(mux, identityapplication.IdentityActionRolesSearch, h.searchIdentityRoles)
	h.registerIdentityAction(mux, identityapplication.IdentityActionRolesValidate, h.validateIdentityRoleAuthoring)
	h.registerIdentityAction(mux, identityapplication.IdentityActionRolesImpactPreview, h.previewIdentityRoleChangeImpact)
	mux.HandleFunc("GET /identity/menus", h.identityPermission("identity.menus.read", h.listIdentityMenus))
	mux.HandleFunc("GET /identity/menus/{menuID}", h.identityPermission("identity.menus.read", h.getIdentityMenu))
	mux.HandleFunc("GET /identity/menus/{menuID}/versions", h.identityPermission("identity.menus.read", h.identityAuthoringVersions("identity.menu", "identity_menu", "menuID", "identity_menu_upserted", "identity_menu_deleted")))
	mux.HandleFunc("POST /identity/menus/{menuID}/validate", h.identityPermission("identity.menus.write", h.validateIdentityMenuAuthoring))
	mux.HandleFunc("PUT /identity/menus/{menuID}", h.identityPermission("identity.menus.write", h.upsertIdentityMenu))
	mux.HandleFunc("DELETE /identity/menus/{menuID}", h.identityPermission("identity.menus.write", h.deleteIdentityMenu))
	h.registerIdentityAction(mux, identityapplication.IdentityActionPermissionsList, h.listIdentityPermissions)
	mux.HandleFunc("GET /identity/roles/{roleID}/menus", h.identityPermission("identity.menus.read", h.listIdentityRoleMenus))
	mux.HandleFunc("GET /identity/roles/{roleID}/menus/versions", h.identityPermission("identity.menus.read", h.identityAuthoringVersions("identity.role_menu_assignment", "identity_role", "roleID", "identity_role_menus_updated")))
	mux.HandleFunc("POST /identity/roles/{roleID}/menus/validate", h.identityPermission("identity.menus.write", h.validateIdentityRoleMenuAssignmentAuthoring))
	mux.HandleFunc("PUT /identity/roles/{roleID}/menus", h.identityPermission("identity.menus.write", h.setIdentityRoleMenus))
	h.registerIdentityAction(mux, identityapplication.IdentityActionRolePermissionsList, h.listIdentityRolePermissions)
	h.registerIdentityAction(mux, identityapplication.IdentityActionRolePermissionsValidate, h.validateIdentityRolePermissionAuthoring)
	h.registerIdentityAction(mux, identityapplication.IdentityActionRolePermissionsPublish, h.publishIdentityRolePermissions)
	mux.HandleFunc("GET /identity/roles/{roleID}/data-scopes", h.identityPermission("identity.data_scopes.read", h.listIdentityRoleDataScopes))
	mux.HandleFunc("POST /identity/roles/{roleID}/data-scopes/validate", h.identityPermission("identity.data_scopes.write", h.validateIdentityRoleDataScopeAuthoring))
	mux.HandleFunc("GET /identity/roles/{roleID}/field-permissions", h.identityPermission("identity.field_permissions.read", h.listIdentityRoleFieldPermissions))
	mux.HandleFunc("POST /identity/roles/{roleID}/field-permissions/validate", h.identityPermission("identity.field_permissions.write", h.validateIdentityRoleFieldPermissionAuthoring))
}
