package identity

import (
	"net/http"

	identitycontract "github.com/domainry/domainry-identity/internal/domain/identity/contract"
)

type routeRegistrar interface {
	HandleFunc(string, func(http.ResponseWriter, *http.Request))
}

func (h *IdentityHandler) RegisterRoutes(mux routeRegistrar) {
	h.registerIdentityAction(mux, "identity.effective_menus.get", h.EffectiveMenus)
	h.registerIdentityAction(mux, "identity.organization_units.list", h.listIdentityOrganizationUnits)
	h.registerIdentityAction(mux, "identity.organization_units.get", h.getIdentityOrganizationUnit)
	h.registerIdentityAction(mux, "identity.organization_units.versions", h.identityAuthoringVersions("identity.organization_unit", "identity_organization_unit", "organizationUnitID", "identity_organization_unit_created", "identity_organization_unit_updated"))
	h.registerIdentityAction(mux, "identity.organization_units.create", h.createIdentityOrganizationUnit)
	h.registerIdentityAction(mux, "identity.organization_units.validate", h.validateIdentityOrganizationUnitAuthoring)
	h.registerIdentityAction(mux, "identity.organization_units.update", h.updateIdentityOrganizationUnit)
	h.registerIdentityAction(mux, "identity.users.list", h.listIdentityUsers)
	h.registerIdentityAction(mux, "identity.users.search", h.searchIdentityUsers)
	h.registerIdentityAction(mux, "identity.accounts.search", h.searchIdentityAccounts)
	h.registerIdentityAction(mux, "identity.users.get", h.getIdentityUser)
	h.registerIdentityAction(mux, "identity.users.deletion_impact", h.getIdentityUserDeletionImpact)
	h.registerIdentityAction(mux, "identity.users.disable_impact", h.getIdentityUserDisableImpact)
	h.registerIdentityAction(mux, "identity.users.versions", h.identityAuthoringVersions("identity.user", "identity_user", "userID", "identity_user_created", "identity_user_updated", "identity_user_disabled", "identity_user_enabled", "identity_user_deleted"))
	h.registerIdentityAction(mux, "identity.users.create", h.createIdentityUser)
	h.registerIdentityAction(mux, "identity.users.validate", h.validateIdentityUserAuthoring)
	h.registerIdentityAction(mux, "identity.users.update", h.updateIdentityUser)
	h.registerIdentityAction(mux, "identity.users.delete", h.deleteIdentityUser)
	h.registerIdentityAction(mux, "identity.users.disable", h.disableIdentityUser)
	h.registerIdentityAction(mux, "identity.users.enable", h.enableIdentityUser)
	h.registerIdentityAction(mux, "identity.users.security_get", h.identityUserSecurity)
	h.registerIdentityAction(mux, "identity.users.effective_access", h.getIdentityEffectiveAccess)
	h.registerIdentityAction(mux, "identity.users.unlock", h.unlockIdentityUser)
	h.registerIdentityAction(mux, identitycontract.IdentityActionUsersForceLogout, h.forceLogoutIdentityUser)
	h.registerIdentityAction(mux, "identity.users.mfa_revoke", h.revokeIdentityUserMFAFactor)
	h.registerIdentityAction(mux, "identity.user_role_assignments.list", h.listIdentityUserRoleAssignments)
	h.registerIdentityAction(mux, "identity.user_role_assignments.search", h.searchIdentityUserRoleAssignments)
	h.registerIdentityAction(mux, "identity.user_role_assignments.assignable_roles", h.listIdentityAssignableRoles)
	h.registerIdentityAction(mux, "identity.user_role_assignments.account_and_roles_update", h.upsertIdentityUserWithRoles)
	h.registerIdentityAction(mux, "identity.user_role_assignments.versions", h.identityAuthoringVersions("identity.user_role_assignment", "identity_user", "userID", "identity_user_role_assigned", "identity_user_role_removed"))
	h.registerIdentityAction(mux, "identity.user_role_assignments.assign", h.assignIdentityUserRole)
	h.registerIdentityAction(mux, "identity.user_role_assignments.validate", h.validateIdentityUserRoleAssignmentAuthoring)
	h.registerIdentityAction(mux, "identity.user_role_assignments.revoke", h.removeIdentityUserRole)
	h.registerIdentityAction(mux, identitycontract.IdentityActionProfileBindingsGet, h.getIdentityProfileBinding)
	h.registerIdentityAction(mux, identitycontract.IdentityActionProfileBindingsCommand, h.executeIdentityProfileBindingCommand)
	h.registerIdentityAction(mux, "identity.principal_context.get", h.getIdentityPrincipalContext)
	h.registerIdentityAction(mux, "identity.access.explain", h.explainIdentityEffectiveAccess)
	h.registerIdentityAction(mux, "identity.access.reverse_index", h.getIdentityAccessReverseIndex)
	h.registerIdentityAction(mux, "identity.access.reports", h.getIdentityAccessGovernanceReports)
	h.registerIdentityAction(mux, "identity.access_reviews.create", h.createIdentityAccessReview)
	h.registerIdentityAction(mux, "identity.access_reviews.list", h.listIdentityAccessReviews)
	h.registerIdentityAction(mux, "identity.access_review_items.decide", h.decideIdentityAccessReviewItem)
	h.registerIdentityAction(mux, "identity.entitlements.batch", h.applyIdentityEntitlementBatch)
	h.registerIdentityAction(mux, "identity.role_requests.list", h.listIdentityRoleRequests)
	h.registerIdentityAction(mux, "identity.role_requests.approve", h.approveIdentityRoleRequest)
	h.registerIdentityAction(mux, "identity.role_requests.reject", h.rejectIdentityRoleRequest)
	h.registerIdentityAction(mux, "identity.roles.list", h.listIdentityRoles)
	h.registerIdentityAction(mux, "identity.roles.get", h.getIdentityRole)
	h.registerIdentityAction(mux, identitycontract.IdentityActionRolesCreate, h.createIdentityRole)
	h.registerIdentityAction(mux, identitycontract.IdentityActionRolesUpdate, h.updateIdentityRole)
	h.registerIdentityAction(mux, identitycontract.IdentityActionRolesDelete, h.deleteIdentityRole)
	h.registerIdentityAction(mux, "identity.roles.governance_detail", h.getIdentityRoleGovernanceDetail)
	h.registerIdentityAction(mux, "identity.roles.versions", h.identityAuthoringVersions("identity.role", "identity_role", "roleID", "identity_role_created", "identity_role_updated", "identity_role_disabled", "identity_role_enabled", "identity_role_deleted"))
	h.registerIdentityAction(mux, "identity.roles.validate_governance", h.validateIdentityGovernance)
	h.registerIdentityAction(mux, "identity.roles.search", h.searchIdentityRoles)
	h.registerIdentityAction(mux, "identity.roles.validate", h.validateIdentityRoleAuthoring)
	h.registerIdentityAction(mux, "identity.roles.impact_preview", h.previewIdentityRoleChangeImpact)
	h.registerIdentityAction(mux, "identity.menus.list", h.listIdentityMenus)
	h.registerIdentityAction(mux, "identity.menus.get", h.getIdentityMenu)
	h.registerIdentityAction(mux, "identity.menus.versions", h.identityAuthoringVersions("identity.menu", "identity_menu", "menuID", "identity_menu_upserted", "identity_menu_deleted"))
	h.registerIdentityAction(mux, "identity.menus.validate", h.validateIdentityMenuAuthoring)
	h.registerIdentityAction(mux, "identity.menus.upsert", h.upsertIdentityMenu)
	h.registerIdentityAction(mux, "identity.menus.delete", h.deleteIdentityMenu)
	h.registerIdentityAction(mux, "identity.permissions.list", h.listIdentityPermissions)
	h.registerIdentityAction(mux, "identity.permissions.set_enabled", h.setIdentityPermissionEnabled)
	h.registerIdentityAction(mux, "identity.role_menus.list", h.listIdentityRoleMenus)
	h.registerIdentityAction(mux, "identity.role_menus.versions", h.identityAuthoringVersions("identity.role_menu_assignment", "identity_role", "roleID", "identity_role_menus_updated"))
	h.registerIdentityAction(mux, "identity.role_menus.validate", h.validateIdentityRoleMenuAssignmentAuthoring)
	h.registerIdentityAction(mux, "identity.role_menus.publish", h.setIdentityRoleMenus)
	h.registerIdentityAction(mux, identitycontract.IdentityActionRolePermissionsList, h.listIdentityRolePermissions)
	h.registerIdentityAction(mux, "identity.role_permissions.validate", h.validateIdentityRolePermissionAuthoring)
	h.registerIdentityAction(mux, identitycontract.IdentityActionRolePermissionsPublish, h.publishIdentityRolePermissions)
	h.registerIdentityAction(mux, identitycontract.IdentityActionRoleFieldPermissionsList, h.listIdentityRoleFieldPermissions)
	h.registerIdentityAction(mux, identitycontract.IdentityActionRoleFieldPermissionsValidate, h.validateIdentityRoleFieldPermissionAuthoring)
	h.registerIdentityAction(mux, identitycontract.IdentityActionRoleFieldPermissionsPublish, h.publishIdentityRoleFieldPermissions)
}
